<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- X-Rail Riser Macro -->
    <xacro:macro name="x_rail_riser" params="namespace:='' prefix:='' parent_link *origin">
        <!-- Build namespace prefix -->
        <xacro:property name="ns_prefix" value="${namespace}/${prefix}"/>

        <!-- Riser Size -->
        <xacro:property name="riser_x_size" value="0.43" />
        <xacro:property name="riser_y_extension" value="0.25" />
        <xacro:property name="riser_y_size" value="0.55" />
        <xacro:property name="riser_z_size" value="0.28" />

        <!-- Riser Origin -->
        <xacro:property name="riser_x_origin" value="0" />
        <xacro:property name="riser_y_origin" value="-0.078" />
        <xacro:property name="riser_z_origin" value="0" />

        <xacro:property name="riser_y_offset" value="0.125" />
        <xacro:property name="riser_z_offset" value="-0.02" />

        <!-- Battery Size -->
        <xacro:property name="battery_z_size" value="0.08" />
        <xacro:property name="battery_z_origin" value="${0.26 + battery_z_size/2}" />

        <!-- X-Rail Riser Link -->
        <link name="${ns_prefix}x_rail_riser_link">
            <visual>
                <origin xyz="${riser_x_origin} ${riser_y_origin} ${riser_z_origin}" rpy="0 0 0"/>
                <geometry>
                    <!-- <mesh filename="package://husky_xarm6_mcr_description/meshes/x_rail_riser.dae" scale="1 1 1"/> -->
                    <!-- <mesh filename="file://$(find husky_xarm6_mcr_description)/meshes/x_rail_riser.dae"/> -->
                    <mesh filename="file://$(find husky_xarm6_mcr_description)/meshes/Platform_Electronics.dae"/>
                </geometry>
            </visual>
            <!-- X-rail collisions -->
            <collision>
                <origin xyz="${riser_x_origin} ${riser_y_offset} ${riser_z_origin + riser_z_offset + riser_z_size/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${riser_x_size} ${riser_y_size + riser_y_extension} ${riser_z_size}"/>
                </geometry>
            </collision>
            <!-- Mounted battery collisions -->
            <collision>
                <origin xyz="0 0 ${battery_z_origin}" rpy="0 0 0"/>
                <geometry>
                    <box size="${riser_x_size} ${riser_y_size} ${battery_z_size}"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0.01142856 0.38887557 0.14875439" rpy="0 0 0"/>
                <mass value="37.70490883"/>
                <inertia
                    ixx="3.0863383" ixy="0.13633027" ixz="-0.05595213"
                    iyy="1.23426261" iyz="0.14585405"
                    izz="3.73292102"/>
            </inertial>
        </link>

        <!-- Joint connecting X-Rail riser to parent -->
        <joint name="${ns_prefix}x_rail_riser_joint" type="fixed">
            <parent link="${parent_link}"/>
            <child link="${ns_prefix}x_rail_riser_link"/>
            <xacro:insert_block name="origin"/>
        </joint>

    </xacro:macro>

</robot>