<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- X-Rail Riser Macro -->
    <xacro:macro name="x_rail_riser" params="namespace:='' prefix:='' parent_link *origin">
        <!-- Build namespace prefix -->
        <xacro:property name="ns_prefix" value="${namespace}/${prefix}"/>
        <xacro:property name="height" value="0.33" />
        <xacro:property name="width" value="0.46" />
        <xacro:property name="depth" value="1.1" />

        <!-- X-Rail Riser Link -->
        <link name="${ns_prefix}x_rail_riser_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <!-- <mesh filename="package://husky_xarm6_mcr_description/meshes/x_rail_riser.dae" scale="1 1 1"/> -->
                    <mesh filename="file://$(find husky_xarm6_mcr_description)/meshes/x_rail_riser.dae"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${width} ${depth} ${height}"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0.01142856 0.38887557 0.14875439" rpy="0 0 0"/>
                <mass value="37.70490883"/>
                <inertia
                    ixx="3.0863383" ixy="0.13633027" ixz="-0.05595213"
                    iyy="1.23426261" iyz="0.14585405"
                    izz="3.73292102"/>
            </inertial>
        </link>

        <!-- Joint connecting X-Rail riser to parent -->
        <joint name="${ns_prefix}x_rail_riser_joint" type="fixed">
            <parent link="${parent_link}"/>
            <child link="${ns_prefix}x_rail_riser_link"/>
            <xacro:insert_block name="origin"/>
        </joint>

    </xacro:macro>

</robot>