controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true   # <-- set true for sim

    joint_state_broadcaster.type: joint_state_broadcaster/JointStateBroadcaster
    platform_velocity_controller.type: diff_drive_controller/DiffDriveController
    wheel_velocity_controller.type: forward_command_controller/ForwardCommandController


platform_velocity_controller:
  ros__parameters:
    use_sim_time: true   # <-- set true for sim
    left_wheel_names:  ["a200_front_left_wheel_joint", "a200_rear_left_wheel_joint"]
    right_wheel_names: ["a200_front_right_wheel_joint", "a200_rear_right_wheel_joint"]

    wheel_separation: 0.555
    wheel_radius: 0.1651
    wheels_per_side: 2         # you’ve got two per side; set 2

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: a200_base_link   # <— IMPORTANT
    enable_odom_tf: false           # you can set true later if you want TF

    cmd_vel_timeout: 0.5
    use_stamped_vel: false

    # linear.x.has_velocity_limits: true
    # linear.x.max_velocity: 1.0
    # linear.x.has_acceleration_limits: true
    # linear.x.max_acceleration: 1.0

    # angular.z.has_velocity_limits: true
    # angular.z.max_velocity: 1.0
    # angular.z.has_acceleration_limits: true
    # angular.z.max_acceleration: 1.0

    open_loop: true
    linear.x.has_velocity_limits: false
    linear.x.has_acceleration_limits: false
    angular.z.has_velocity_limits: false
    angular.z.has_acceleration_limits: false
    velocity_rolling_window_size: 1
    publish_cmd: true

wheel_velocity_controller:
  ros__parameters:
    joints:
      - a200_front_left_wheel_joint
      - a200_rear_left_wheel_joint
      - a200_front_right_wheel_joint
      - a200_rear_right_wheel_joint
    interface_name: velocity