moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - xarm6_traj_controller

  xarm6_traj_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - xarm6_joint1
      - xarm6_joint2
      - xarm6_joint3
      - xarm6_joint4
      - xarm6_joint5
      - xarm6_joint6

trajectory_execution:
  manage_controllers: false
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
